### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by tammo0** [OpenParliamentTV/OpenParliamentTV-NEL#24]
Hi @alexabruck and @OpenHypervideo 

First of all, thank you for the great work.

It is a bit hard to get into the project, because the readme seems to be out of date.

There are some infos missing like
- requirements (e.g. pip3 to install "SPARQLWrapper" or pipenv install "requests")
- workflows (like to have the data directories available before running the scripts, they will not be created)
- how-tos (like there is the need to pseudo install optv-nel by "pip3 install -e src/", or from where to call the scripts so the directories will be found)

Would be really great and appreciated if these infos may added to the readme

thanks

**Comment by alexabruck** [comment]
Good points!
I hope it is clearer now: https://github.com/OpenParliamentTV/OpenParliamentTV-NEL/commit/55bcc1ce4f496e768e1ee54c2470b52b628f7939. Now only 1 command is needed to install dependencies and the internal packages: `pipenv install` which will draw the dependencies from `Pipfile` and/or `Pipfile.lock`
