### ISSUE TITLE
parties_abgeordnetenwatch - parties.json

### ISSUE THREAD

**Issue by tammo0** [OpenParliamentTV/OpenParliamentTV-NEL#25]
Hi,

following the readme, all files should be run in nummeric order, to collect all data and get the final output files.

I have a problem running [d04_generate_mappings](../blob/master/src/optv_nel/d04_generate_mappings.py) which seems to require the file [data/01_raw/parties_abgeordnetenwatch/parties.json](../blob/master/data/01_raw/parties_abgeordnetenwatch/parties.json).

I assume it should be generated by [d01_query_parties_abgeordnetenwatch.py](../blob/master/src/optv_nel/d01_query_parties_abgeordnetenwatch.py) but this contains only "TODO".
So how do i get this file generated which is needed to run step 4? Just download it from this repo?

Thanks in advance

**Comment by alexabruck** [comment]
Seeing the issues you run into, I assume you deleted the data folder entirely before running the scripts? That is actually is a good practice, I will add it to the README. And you are right the abgeordneten watch parties should be requested and updated whenever we run a new dump!

**Comment by alexabruck** [comment]
Should be fixed now: https://github.com/OpenParliamentTV/OpenParliamentTV-NEL/commit/204617991ee3f28a361579fea75eb129a8e1e678
