### ISSUE TITLE
05_enhanced - parties.json

### ISSUE THREAD

**Issue by tammo0** [OpenParliamentTV/OpenParliamentTV-NEL#27]
Hi!

i assume directory /data/05_enhanced contains the final files.

But as the script [d05_enhance_parties.py](../blob/master/src/optv_nel/d05_enhance_parties.py) doesn't contain any code, how does the file [parties.json](../blob/master/data/05_enhanced/parties.json) which is available in this repo, gets in there?

Thanks in advance for your answers

**Comment by alexabruck** [comment]
Thanks, it should be fixed now!
https://github.com/OpenParliamentTV/OpenParliamentTV-NEL/commit/b3d475f15a05ce88035f77cbe993aff9585e2af6
